In [5]:
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import operator
# file = open()
X = []
y = []   #decoy, target
# Lines = file.readlines()
count = 0
with open("/Users/claricepark/Discriminant-Analysis/20220727_TypeAcomplex_Elastase_S2-A3_1_10495_nopd.sqt") as fp:
    while True:                
        line = fp.readline()
        if not line:
            break
        
        if line.startswith("H\t"):
            continue     
                
        sline = line.strip()                
        count += 1
        # print(sline)          
        # if(count>200):
        #     break
        
        decoy_label = 1
        if line.startswith("M\t1"):    
            
            # print (line.strip())  
            xcorr = line.split("\t")[5]
            # print(xcorr)
            
            lline = fp.readline()
            
            if (lline.split("\t")[1].startswith("Reverse")):                
               decoy_label = 0
            # print (lline.strip())
            # print (decoy_label)   
            # print ("l line\t", lline.split("\t")[1])
            while True:
                m2line = fp.readline()
                if(m2line.startswith("M\t2")):
                    break;
                
            # m2line = fp.readline()
            # print ("m2  line\t", m2line.strip())
            deltacn = m2line.split("\t")[4]
            
            # print("delta cn\t", deltacn)
            X.append([xcorr, deltacn])
            y.append(decoy_label)
            
        
# print (X)
# print (y)
clf = LinearDiscriminantAnalysis()
clf.fit(X, y)
print(clf.predict([[3.2, 0.001]]))
print(clf.predict([[1.2, 0.0001]]))
print(clf.predict([[1.05, 0.0001]]))
print(clf.predict([[0.002, 0.00001]]))

print(clf.predict_proba([[3.2, 0.001]]))
print(clf.predict_proba([[1.2, 0.0001]]))
print(clf.predict_proba([[1.05, 0.0001]]))
print(clf.predict_proba([[0.002, 0.00001]]))

[0]
[0]
[0]
[0]
[[0.50921021 0.49078979]]
[[0.5178699 0.4821301]]
[[0.51851791 0.48148209]]
[[0.52304491 0.47695509]]
